### ISSUE TITLE
add LICENSE information

### ISSUE THREAD

**Issue by mroth** [mroth/sseserver#1]
Realized I forgot to do this years ago, even though the intention was for the project to be freely licensed. So might as well use this as an opp. to research and really pick the best license here.

**Comment by adrianmxb** [comment]
hey @mroth,
any news on this?

**Comment by mroth** [comment]
@adrianmxb No news, I'd basically just been waiting until someone said they needed it to be licensed. 🤷

Do you have a current need for a licensed version for use? If so, what (if any) licensing constraints does your organization have (as a hypothetical example, would AGPL prevent its adoption?)
