### ISSUE TITLE
Unable to run in a docker container

### ISSUE THREAD

**Issue by steddyman** [mroth/sseserver#15]
I've been trying to get a simple web server script deployed into a docker container.  The script called server.go will work fine locally and hosts the SSE server as expected.

The same script compiled into a docker container throws the following error.  This is the same on my Mac or trying to run it on a Linux container in the cloud.  No matter what I have tried I get the same error.  Not even the very first fmt.Println is executed:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x650e86]

goroutine 1 [running]:
debug/elf.(*Section).ReadAt(0xc000200000?, {0xc0001b2480?, 0x270?, 0x24?}, 0x40?)
	<autogenerated>:1 +0x26
archive/zip.readDirectoryEnd({0x76ff40, 0xc00019ad00}, 0x210)
	/usr/local/go/src/archive/zip/reader.go:526 +0xf5
archive/zip.(*Reader).init(0xc000186a10, {0x76ff40?, 0xc00019ad00}, 0x210)
	/usr/local/go/src/archive/zip/reader.go:97 +0x5c
archive/zip.NewReader({0x76ff40, 0xc00019ad00}, 0x210)
	/usr/local/go/src/archive/zip/reader.go:90 +0x5e

**Comment by steddyman** [comment]
It isn't only in a docker container.  If I compile the code using 'go build', it also reports the same errors on startup when running the native binary.

Running GO RUN SERVER.GO works every time without error.

**Comment by mroth** [comment]
Since you are getting this error trying to launch a binary but not when this module code is being executed, this sounds like you some sort of issue with your build toolchain which is unrelated to this module.  I'd try a simple hello world script and build it in the same fashion and see if you get the error.  If the distinction is somehow the inclusion of this module, then please re-open the issue with sample code. Thanks!

**Comment by steddyman** [comment]
Thanks.  The error seems to have been two-fold:
1. The overrides for GOOS and GOARCH do not work during build
2. Having a go.sum and go.mod in the directory broke builds

For 1, I have found if i build it on the target system directly rather than using these variables, it works.  It would not work using the Docker Hub online build, or Mac build.

For 2, deleting these and just running GO BUILD with the only files in the directory being my script worked.

Thanks for your response, and great module.
