### ISSUE TITLE
cluster of sse

### ISSUE THREAD

**Issue by nicola-spb** [mroth/sseserver#5]
How can I use sseserver in cluster?

**Comment by mroth** [comment]
Hi @nicola-spb, can you provide more details about what you are trying to do?

The sseserver library handles the outgoing sending of the messages, how you route to your server nodes is likely going to be highly dependent on what your internal topography looks like.

For example, in the case of Emojitracker.com, the internal message queue is handled via a Redis PUBSUB server, which each [emojitrack-streamer server](https://github.com/emojitracker/emojitrack-gostreamer) consumes and then utilizes this sseserver library to send out to clients.

Overall server flow:
![](https://github.com/mroth/emojitracker/raw/master/resources/infrastructure_diagram.png)

Internal logic of an emojitrack-server, which consumes the redis feeds, does some transformation logic, and then publishes a number of namespaces streams via sseserver:
![](https://camo.githubusercontent.com/d1d37b4fee09ba3c6387b6e6f42931e193a45215/687474703a2f2f662e636c2e6c792f6974656d732f31533238326a334130483037333832783371324c2f6469616772616d2e737667)

**Comment by nicola-spb** [comment]
I wanna use sseserver but I have some servers. Can sseserver do synchronizion between some sseserver instances? If user connected to first sever and connected to other server by mobile then will he give notification to both devices?

**Comment by mroth** [comment]
sseserver just handles the transport.  An example of synchronization across many nodes is in the reply above -- it will most likely be specific to your applicaiton/business logic.
