### ISSUE TITLE
use sseserver with chi-router 

### ISSUE THREAD

**Issue by joselbr2099** [mroth/sseserver#6]
How could I use sseserver with chi-router?  I'm really very confused

**Comment by mroth** [comment]
I have no familiarity with chi-router but from a quick glance at their README:

> chi uses standard net/http request handlers.

From https://github.com/go-chi/chi#request-handlers

As [sseserver.Server](https://godoc.org/github.com/mroth/sseserver#Server) implements the `http.Handler` interface, you can use it just like any other standard Go HTTP handler in Chi.

Closing as an upstream documentation issue with chi-router, not related to sseserver itself.
