### ISSUE TITLE
Query on "Performance" information from README

### ISSUE THREAD

**Issue by rebootcode** [mroth/sseserver#8]
You mentioned:

> In my preliminary benchmarking (on v1.0, circa 2014) this can handle ~100K/sec messages broadcast across ~1000 open HTTP connections on a 3.4GHz Intel Core i7 (using a single core, e.g. with GOMAXPROCS=1)

You didn't mention RAM used?

- Do you have a performance benchmark against "WebSocket"? for the same level of usage?

**Comment by mroth** [comment]
I no longer have the benchmark data stored from 2014, so I don't know what the memory usage was at that time. I suggest profiling for your own use case on production hardware.

I did not compare against websockets, nor do a suggest picking between the two protocols based on performance characteristics, there are other practical considerations that will have more bearing as to which is most appropriate for your use case.
